### ISSUE TITLE
is_finished = None for all titles in library

### ISSUE THREAD

**Issue by dimyr7** [mkb79/Audible#17]
I am trying to get the "finished" status of all titles in my library. I'm able to log in successfully and retrieve the titles, but the "is_finished" attribute is always set to None. Here is the code snippet I'm using:
```
auth = audible.FileAuthenticator("audible.save")
print(auth.adp_token)
client = audible.AudibleAPI(auth)
library, _ = client.get("library")

for book in library["items"]:
    print(book['is_finished'])
```

I'm guessing this is more a problem with the API returning that value but the mobile app must be retrieving it somehow.

**Comment by mkb79** [comment]
Hi,

the problem is this line of code 

`library, _ = client.get("library")`.

You have to tell the api which informations you want. Therefore you use the `response_groups` param. 

Please try this line of code


`library, _ = client.get("library", response_groups="is_finished")`


You can take a look at https://audible.readthedocs.io/en/latest/misc/external_api.html. There you can find all (known) response groups for the library endpoint.
