### ISSUE TITLE
encryptedPwd

### ISSUE THREAD

**Issue by RahulKasireddy** [mkb79/Audible#77]
New login page requires this parameter, it gets encrypted using aes128 gcm with jwk rsa. I didn't get the exact code to mimic the process. Can anybody help me to get the encryption part?

**Comment by mkb79** [comment]
Hi. As far as I know Amazon accepts unencrypted passwords for login at this moment. Or have they changed something?

**Comment by RahulKasireddy** [comment]
I was unable to login using the metadata, Can you please check it once.

**Comment by mkb79** [comment]
That's strange. `metadata1` is not required to login. You can set them to `metadata1=false`! 

What have you tried and at which point you failed? Can you provide your code please?

**Comment by RahulKasireddy** [comment]
Can you please share me the cookies required for login?

**Comment by RahulKasireddy** [comment]
It shows me captcha

**Comment by mkb79** [comment]
It is difficult to help you. You have to tell me what exactly you are up to. As I understand it, you want to register to Amazon. Do you use my Audible package for this?

Can you possibly provide me with the code that you are using?

PS: Captchas usually appear on Amazon when something is wrong. This could be a bot identification or something was not delivered as expected. If you want to log into Amazon as an Audible device, you must use the initial cookies. Otherwise you will get a captcha. The same thing happens if the entered user does not exist or the password has been entered incorrectly several times.
